site_name:        SeimicInversion.jl
repo_url:         https://github.com/pawbz/SeimicInversion.jl
site_description: Description
site_author:      pawbz
theme: readthedocs

extra_css:
          - assets/Documenter.css

extra_javascript:
          - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
              - assets/mathjaxhelper.js

markdown_extensions:
          - codehilite
          - extra
          - tables
          - fenced_code
          - mdx_math


extra_css:
          - assets/Documenter.css

docs_dir: 'build'

pages:
          - Home: index.md
          - Tutorial:
              - Title 1: tutorials/page1.md
          - Another Section:
              - Title 1: modeling/page1.md


